### ISSUE TITLE
Data summaries - download and unzip most recent master version of portal

### ISSUE THREAD

**Issue by skmorgane** [weecology/PortalDataSummaries#10]

**Comment by sdtaylor** [comment]
There is code to do this here  https://github.com/weecology/portalPredictions/blob/master/forecast_tools.R#L241

**Comment by gmyenni** [comment]
I added @sdtaylor 's functions in `GetData.R` .https://github.com/weecology/PortalDataSummaries/pull/11 We just need to decide where to put the unzipped data. Wouldn't it be in keeping with an R package to put it in the package folder? Then it wouldn't interfere with our repos (mine at least is in the base folder)?

**Comment by sdtaylor** [comment]
The default for most packages is to put it in the working directory. which I think is reasonable. when we're working in the portalPredictions project these it will be downloaded to that folder.

**Comment by ethanwhite** [comment]
Implemented in 807aeb5e86a911f38241946d62ac99f43353faf7.
