### ISSUE TITLE
Discuss usage of new_moon_numbers.r

### ISSUE THREAD

**Issue by ethanwhite** [weecology/PortalDataSummaries#18]
As part of preparing to turn this repo into a package we need to understand how `new_moon_numbers.r` is being used and potentially convert it to a function.

Is this basically a helper script that is used to periodically update the `moon_dates.csv` table in `PortalData`?

**Comment by gmyenni** [comment]
Yeah, I believe it just adds rows to `moon_dates.csv`. So I think we should move it to [DataCleaningScripts](https://github.com/weecology/PortalData/tree/master/DataCleaningScripts). It's just one of those scripts really used only by us. I don't think we need it for anything in Data Summaries.

**Comment by ethanwhite** [comment]
Sounds good to me. As far as I'm concerned you can go ahead and move it at your leisure.

**Comment by emchristensen** [comment]
I'll go ahead and move it, I've been meaning to do some work making it more robust anyway
