### ISSUE TITLE
Improve namespace usage

### ISSUE THREAD

**Issue by ethanwhite** [weecology/PortalDataSummaries#25]
In #24 I've just used full blown imports of all of the packages we're currently loading using `library`. This really pollutes the namespace which isn't good practice. We should do one of the following:

1. Make all calls to packages from external functions explicit by using the package name, e.g., `dplyr::left_join`
2. Add individual function imports to the docstrings and process them using `roxygen2`, e.g., `# @importFrom dplyr left_join`

I have a personal preference for (1) and think I've seen Hadley Wickham recommend this, but I'm flexible.

**Comment by gmyenni** [comment]
I started doing option one in the weather function. . . #36

**Comment by emchristensen** [comment]
Ellen and I finished this.  Pull request ready for review

**Comment by gmyenni** [comment]
Oops, it looks like #39 is failing. Is someone still working on this? @emchristensen @bleds22e

**Comment by emchristensen** [comment]
I thought we were done -- I don't understand what's failing
