### ISSUE TITLE
can't find file

### ISSUE THREAD

**Issue by sdtaylor** [weecology/PortalDataSummaries#29]
I just installed the packaged version and I'm getting this error. It's not putting the slash after the ~

> PortalDataSummaries::abundance()
Loading required package: bitops
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: replacing previous import ‘dplyr::intersect’ by ‘lubridate::intersect’ when loading ‘PortalDataSummaries’ 
2: replacing previous import ‘dplyr::union’ by ‘lubridate::union’ when loading ‘PortalDataSummaries’ 
3: replacing previous import ‘dplyr::setdiff’ by ‘lubridate::setdiff’ when loading ‘PortalDataSummaries’ 
4: replacing previous import ‘RCurl::complete’ by ‘tidyr::complete’ when loading ‘PortalDataSummaries’ 
5: In file(file, "rt") :
  cannot open file '~PortalData/Rodents/Portal_rodent.csv': No such file or directory

**Comment by ethanwhite** [comment]
These are probably all fixed in #28 if you want to test/review it.

**Comment by ethanwhite** [comment]
@sdtaylor - try reinstalling now and see if merging #29 solves the problem.

**Comment by sdtaylor** [comment]
that works but now it can't find a different file. I tracked it down in #30
